version: '3.2'
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres_db
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    container_name: postgres_db
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=Car_Dealership
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - $PWD/../output
    